### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by nhanntdl** [intership0221/nguyenquangduyportfolio#2]
Dear @Nguyeeenduy ,

Em hãy dùng photoshop thiết kế anh trang web dùng để giới thiệu về bản thân em như một CV công việc.

Start date: 02/07/2021 AM
End date: 02/08/2021 AM

Thanks,
TrungNhan.

**Comment by Nguyeeenduy** [comment]
Dear @nhanntdl ,

Em sẽ nhận task này
Estimate: 8 tiếng 

Thanks,
QuangDuy.

**Comment by Nguyeeenduy** [comment]
Dear @nhanntdl 

Hiện tại phần photoshop em thực hiện được tới đây anh xem thử và cho em ý kiến nhé
![image](https://user-images.githubusercontent.com/66856879/107136757-9e4f1500-6938-11eb-980e-dcce74dd9416.png)

Thanks,
QuangDuy

**Comment by Nguyeeenduy** [comment]
Dear @nhanntdl 

Em thực hiện lại nó được như vậy anh xem thử được không ạ
![image](https://user-images.githubusercontent.com/66856879/107139387-62727a80-694d-11eb-8a4f-565e44d275e5.png)

Thanks,
QuangDuy

**Comment by Nguyeeenduy** [comment]
Dear @nhanntdl 

Em đã hoàn thành task này ạ.
![image](https://user-images.githubusercontent.com/66856879/107144799-200e6500-6970-11eb-8295-66529bb774fc.png)

Thanks,
QuangDuy

**Comment by nhanntdl** [comment]
Dear @Nguyeeenduy ,

Anh thấy ổn rồi đó em.
Tiến hành code nhé em

Thanks,
TrungNhan
