### ISSUE TITLE
Coding

### ISSUE THREAD

**Issue by nhanntdl** [intership0221/nguyenquangduyportfolio#3]
Dear @Nguyeeenduy ,

Sau khi đã thiết kế giao diện cho trang web của mình ở task #2 , nhờ em tiến hành code giúp anh

Start date: 02/08/2021
End date: 02/11/2021

Thanks,
TrungNhan

**Comment by Nguyeeenduy** [comment]
Dear @nhanntdl 

Em sẽ nhận task này 

Estimate: 24 tiếng

Thanks,
QuangDuy

**Comment by Nguyeeenduy** [comment]
Dear @nhanntd

Hiện tại em đã thực hiện phần giao diện, anh xem giúp em cần thêm sửa những gì nha anh
https://github.com/intership0221/nguyenquangduyportfolio/tree/coding

Thanks,
QuangDuy

**Comment by Nguyeeenduy** [comment]
Dear @nhanntdl 

I have update the class name
https://github.com/intership0221/nguyenquangduyportfolio/tree/coding

Thanks,
QuangDuy

**Comment by nhanntdl** [comment]
Dear @Nguyeeenduy ,

Please help me push your source code to GitHub to me for review.

Thanks,
TrungNhan
