### ISSUE TITLE
Research about BEM naming convention

### ISSUE THREAD

**Issue by nhanntdl** [intership0221/nguyenquangduyportfolio#4]
Dear @Nguyeeenduy ,

Please help me research about BEM naming convention.
Start date: 02/09/2021 09:10
End date: 02/09/2021 13:00

Thanks,
TrungNhan

**Comment by Nguyeeenduy** [comment]
Dear @nhanntdl 

I will receive this task
Estimate: 5 hours

Thanks,
QuangDuy

**Comment by Nguyeeenduy** [comment]
Dear @nhanntdl 

I have completed the work you assigned
https://drive.google.com/file/d/1F7ZYy2-7L6W5_vOHMRJ-ALpe1pSPYxeo/view?usp=sharing

Thanks,
QuangDuy
